# Generated by Django 3.1.1 on 2020-10-29 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
        ('account_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelStaffInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hotel_manager', models.BooleanField(default=False)),
                ('is_hotel_owner', models.BooleanField(default=False)),
                ('is_waiter', models.BooleanField(default=False)),
                ('shift_start', models.TimeField(blank=True, null=True)),
                ('shift_end', models.TimeField(blank=True, null=True)),
                ('nid', models.CharField(blank=True, max_length=50, null=True)),
                ('shift_days', models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=20, null=True)),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_staff', to='restaurant.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_staff', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
