# Generated by Django 3.1.1 on 2020-10-31 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0002_hotelstaffinformation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelstaffinformation',
            old_name='is_hotel_manager',
            new_name='is_manager',
        ),
        migrations.RenameField(
            model_name='hotelstaffinformation',
            old_name='is_hotel_owner',
            new_name='is_owner',
        ),
    ]
