# Generated by Django 3.1.1 on 2020-11-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0003_auto_20201031_1903'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='hotelstaffinformation',
            constraint=models.UniqueConstraint(fields=('user', 'restaurant'), name='staff_per_restaurant'),
        ),
    ]
