# Generated by Django 3.1.1 on 2020-10-25 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0003_auto_20201025_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='created_at',
        ),
    ]
