# Generated by Django 3.1.1 on 2020-11-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0006_hotelstaffinformation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelstaffinformation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
