# Generated by Django 3.1.1 on 2020-11-05 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0007_auto_20201105_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelstaffinformation',
            name='shift_days',
        ),
    ]
