# Generated by Django 3.1.1 on 2020-11-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0009_auto_20201105_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='email',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='email_address',
            field=models.EmailField(blank=True, max_length=35, null=True),
        ),
    ]
