# Generated by Django 3.1.1 on 2020-11-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0012_hotelstaffinformation_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='last_name',
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='hotelstaffinformation',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
