# Generated by Django 3.1.1 on 2020-11-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0013_auto_20201124_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
