# Generated by Django 3.1.1 on 2020-12-03 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0020_auto_20201203_1742'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fcm',
        ),
    ]
