# Generated by Django 3.1.1 on 2020-12-06 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0022_fcmdevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFcmDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255)),
                ('device_type', models.CharField(choices=[('web', 'web'), ('ios', 'ios'), ('android', 'android')], default='android', max_length=25)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_fcm_devices', to='account_management.customerinfo')),
            ],
        ),
        migrations.CreateModel(
            name='StaffFcmDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255)),
                ('device_type', models.CharField(choices=[('web', 'web'), ('ios', 'ios'), ('android', 'android')], default='android', max_length=25)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('hotel_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_fcm_devices', to='account_management.hotelstaffinformation')),
            ],
        ),
        migrations.DeleteModel(
            name='FcmDevice',
        ),
    ]
