# Generated by Django 3.1.1 on 2020-12-10 08:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0023_auto_20201206_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerfcmdevice',
            name='token',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stafffcmdevice',
            name='token',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
