# Generated by Django 3.1.4 on 2020-12-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0025_otpuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpuser',
            name='otp_code',
            field=models.IntegerField(null=True),
        ),
    ]
