# Generated by Django 3.1.4 on 2020-12-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0026_auto_20201227_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerfcmdevice',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
