# Generated by Django 3.1.4 on 2020-12-28 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0027_auto_20201228_0520'),
    ]

    operations = [
        migrations.CreateModel(
            name='FcmNotificationStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel_staff', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account_management.stafffcmdevice')),
            ],
        ),
    ]
