# Generated by Django 3.1.4 on 2020-12-28 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0028_fcmnotificationstaff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcmnotificationstaff',
            name='hotel_staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account_management.stafffcmdevice'),
        ),
    ]
