# Generated by Django 3.1.4 on 2020-12-29 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0029_auto_20201228_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerfcmdevice',
            name='device_id',
            field=models.IntegerField(default=3),
        ),
    ]
