# Generated by Django 3.1.4 on 2020-12-29 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0030_auto_20201229_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerfcmdevice',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
