# Generated by Django 3.1.4 on 2020-12-29 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0031_auto_20201229_0541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerfcmdevice',
            name='device_id',
        ),
    ]
