# Generated by Django 3.1.4 on 2020-12-29 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0032_remove_customerfcmdevice_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerfcmdevice',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
