# Generated by Django 3.1.4 on 2020-12-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0033_customerfcmdevice_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stafffcmdevice',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
