# Generated by Django 3.1.4 on 2020-12-29 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0034_auto_20201229_0557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fcmnotificationstaff',
            old_name='hotel_staff',
            new_name='staff_device',
        ),
    ]
