# Generated by Django 3.1.1 on 2020-12-30 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0058_auto_20201228_0521'),
        ('account_management', '0035_auto_20201229_0620'),
    ]

    operations = [
        migrations.CreateModel(
            name='FcmNotificationCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account_management.customerfcmdevice')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
        ),
    ]
