# Generated by Django 3.1.4 on 2021-01-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0037_fcmnotificationcustomer_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelstaffinformation',
            name='is_chef',
            field=models.BooleanField(default=False),
        ),
    ]
