# Generated by Django 3.1.4 on 2021-07-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0038_hotelstaffinformation_is_chef'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='password2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='confirm password'),
        ),
    ]
