# Generated by Django 3.1.1 on 2020-11-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_restaurantcontactperson_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='service_charge_percentage',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='service_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='service_charge_is_percentage',
            field=models.BooleanField(default=False),
        ),
    ]
