# Generated by Django 3.1.1 on 2020-11-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20201102_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='logo',
            field=models.FileField(blank=True, default='', upload_to=''),
            preserve_default=False,
        ),
    ]
