# Generated by Django 3.1.1 on 2020-11-03 10:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20201102_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='FoodExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='FoodOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_option', to='restaurant.food')),
            ],
        ),
        migrations.CreateModel(
            name='FoodOptionExtraType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FoodOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantPromoCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('code', models.CharField(max_length=5, unique=True)),
                ('details', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='subscription_ends',
            field=models.DateField(default=datetime.datetime(2020, 11, 3, 10, 31, 7, 36225, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurantcontactperson',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_persons', to='restaurant.restaurant'),
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_no', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='restaurant.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='OrderedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('food_extra', models.ManyToManyField(blank=True, related_name='ordered_items', to='restaurant.FoodExtra')),
                ('food_option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordered_items', to='restaurant.foodoption')),
                ('food_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_items', to='restaurant.foodorder')),
            ],
        ),
        migrations.AddField(
            model_name='foodorder',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_orders', to='restaurant.table'),
        ),
        migrations.AddField(
            model_name='foodoption',
            name='option_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_options', to='restaurant.foodoptionextratype'),
        ),
        migrations.AddField(
            model_name='foodextra',
            name='extra_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_extras', to='restaurant.foodoptionextratype'),
        ),
        migrations.AddField(
            model_name='foodextra',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_extra', to='restaurant.food'),
        ),
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='foods', to='restaurant.foodcategory'),
        ),
        migrations.AddField(
            model_name='food',
            name='promotion_category',
            field=models.ManyToManyField(blank=True, to='restaurant.RestaurantPromoCategory'),
        ),
        migrations.AddField(
            model_name='food',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food', to='restaurant.restaurant'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurants', to='restaurant.subscription'),
        ),
    ]
