# Generated by Django 3.1.1 on 2020-11-04 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20201103_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcategory',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='food_category', to='restaurant.restaurant'),
            preserve_default=False,
        ),
    ]
