# Generated by Django 3.1.1 on 2020-11-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_foodcategory_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='promotion_category',
        ),
        migrations.RemoveField(
            model_name='foodcategory',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='food',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='food',
            name='is_top',
            field=models.BooleanField(default=False),
        ),
    ]
