# Generated by Django 3.1.1 on 2020-11-04 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_auto_20201104_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodextra',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_extras', to='restaurant.food'),
        ),
        migrations.AlterField(
            model_name='foodoption',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_options', to='restaurant.food'),
        ),
    ]
