# Generated by Django 3.1.1 on 2020-11-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0006_hotelstaffinformation_image'),
        ('restaurant', '0008_auto_20201104_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='staff_assigned',
            field=models.ManyToManyField(blank=True, to='account_management.HotelStaffInformation'),
        ),
    ]
