# Generated by Django 3.1.1 on 2020-11-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_table_is_occupied'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='ingredients',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodorder',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordereditem',
            name='status',
            field=models.CharField(choices=[('0_ORDER_INITIALIZED', 'ORDER_INITIALIZED'), ('1_ORDER_PLACED', 'ORDER_PLACED'), ('2_PROCESSING', 'PROCESSING'), ('3_IN_TABLE', 'IN_TABLE')], default='0_ORDER_INITIALIZED', max_length=120),
        ),
    ]
