# Generated by Django 3.1.1 on 2020-11-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_auto_20201108_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodorder',
            name='status',
            field=models.CharField(choices=[('0_ORDER_INITIALIZED', 'ORDER_INITIALIZED'), ('1_ORDER_PLACED', 'ORDER_PLACED'), ('2_ORDER_CONFIRMED', 'ORDER_CONFIRMED'), ('3_PROCESSING', 'PROCESSING'), ('4_IN_TABLE', 'IN_TABLE'), ('5_PAID', 'PAID'), ('6_CANCELLED', 'CANCELLED')], default='0_ORDER_INITIALIZED', max_length=120),
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='status',
            field=models.CharField(choices=[('0_ORDER_INITIALIZED', 'ORDER_INITIALIZED'), ('1_ORDER_PLACED', 'ORDER_PLACED'), ('2_ORDER_CONFIRMED', 'ORDER_CONFIRMED'), ('3_PROCESSING', 'PROCESSING'), ('4_IN_TABLE', 'IN_TABLE'), ('5_CANCELLED', 'CANCELLED')], default='0_ORDER_INITIALIZED', max_length=120),
        ),
    ]
