# Generated by Django 3.1.1 on 2020-11-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_auto_20201108_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditem',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
