# Generated by Django 3.1.1 on 2020-11-10 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0017_auto_20201109_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodExtraType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FoodOptionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='foodextra',
            name='extra_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_extras', to='restaurant.foodextratype'),
        ),
        migrations.AlterField(
            model_name='foodoption',
            name='option_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_options', to='restaurant.foodoptiontype'),
        ),
        migrations.DeleteModel(
            name='FoodOptionExtraType',
        ),
    ]
