# Generated by Django 3.1.1 on 2020-11-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0018_auto_20201110_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodorder',
            name='status',
            field=models.CharField(choices=[('0_ORDER_INITIALIZED', 'ORDER_INITIALIZED'), ('1_ORDER_PLACED', 'Waiting for Verification'), ('2_ORDER_CONFIRMED', 'In Kitchen'), ('3_IN_TABLE', 'Served on Table'), ('4_PAID', 'Paid'), ('5_CANCELLED', 'Cancelled')], default='0_ORDER_INITIALIZED', max_length=120),
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='status',
            field=models.CharField(choices=[('0_ORDER_INITIALIZED', 'ORDER_INITIALIZED'), ('1_ORDER_PLACED', 'Waiting for Verification'), ('2_ORDER_CONFIRMED', 'In Kitchen'), ('3_IN_TABLE', 'Served on Table'), ('4_CANCELLED', 'Cancelled')], default='0_ORDER_INITIALIZED', max_length=120),
        ),
    ]
