# Generated by Django 3.1.1 on 2020-11-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0019_auto_20201111_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodoptiontype',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
