# Generated by Django 3.1.1 on 2020-11-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0021_foodcategory_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
