# Generated by Django 3.1.1 on 2020-11-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0022_restaurant_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodextratype',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
