# Generated by Django 3.1.1 on 2020-11-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0026_auto_20201115_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='order_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
