# Generated by Django 3.1.1 on 2020-11-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0029_auto_20201117_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodextra',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='foodoption',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='grand_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='service_charge',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='tax_percentage',
            field=models.FloatField(default=0.0),
        ),
    ]
