# Generated by Django 3.1.1 on 2020-11-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0032_auto_20201124_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodorder',
            name='discount_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='foodorder',
            name='grand_total_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='foodorder',
            name='payable_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='foodorder',
            name='service_charge',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='foodorder',
            name='tax_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='foodorder',
            name='tax_percentage',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='foodorder',
            name='total_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
