# Generated by Django 3.1.1 on 2020-11-25 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0033_auto_20201125_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount', to='restaurant.restaurant'),
        ),
    ]
