# Generated by Django 3.1.1 on 2020-11-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0035_auto_20201126_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='trade_licence_no',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='vat_registration_no',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
