# Generated by Django 3.1.1 on 2020-11-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0014_useraccount_first_name'),
        ('restaurant', '0036_auto_20201126_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='staff_assigned',
            field=models.ManyToManyField(blank=True, related_name='table', to='account_management.HotelStaffInformation'),
        ),
    ]
