# Generated by Django 3.1.1 on 2020-12-03 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0016_auto_20201203_0843'),
        ('restaurant', '0039_discount_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account_management.customerinfo'),
        ),
    ]
