# Generated by Django 3.1.1 on 2020-12-06 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0040_foodorder_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodorder',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_orders', to='restaurant.restaurant'),
        ),
    ]
