# Generated by Django 3.1.4 on 2020-12-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0045_auto_20201215_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payable_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
