# Generated by Django 3.1.1 on 2020-12-21 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0048_auto_20201221_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='foods',
        ),
        migrations.AddField(
            model_name='slider',
            name='food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sliders', to='restaurant.food'),
        ),
    ]
