# Generated by Django 3.1.1 on 2020-12-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0050_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='order_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
