# Generated by Django 3.1.1 on 2020-12-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0053_auto_20201224_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantmessages',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
