# Generated by Django 3.1.1 on 2020-12-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0055_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='payment_type',
            field=models.ManyToManyField(blank=True, null=True, to='restaurant.Payment_type'),
        ),
    ]
