# Generated by Django 3.1.4 on 2020-12-27 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0056_restaurant_payment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Payment_type',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='payment_type',
            field=models.ManyToManyField(blank=True, null=True, to='restaurant.PaymentType'),
        ),
    ]
