# Generated by Django 3.1.1 on 2020-12-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0058_auto_20201228_0521'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_id', models.FloatField(blank=True, null=True)),
                ('force_update', models.BooleanField(default=False)),
                ('is_customer', models.BooleanField(default=False)),
                ('is_waiter', models.BooleanField(default=False)),
            ],
        ),
    ]
