# Generated by Django 3.1.4 on 2020-12-31 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0036_fcmnotificationcustomer'),
        ('restaurant', '0059_versionupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodOrderLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('order_status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_order_logs', to='restaurant.foodorder')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_order_logs', to='account_management.hotelstaffinformation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
