# Generated by Django 3.1.4 on 2020-12-31 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0060_auto_20201230_1139'),
        ('restaurant', '0060_foodorderlog'),
    ]

    operations = [
    ]
