# Generated by Django 3.1.4 on 2021-01-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0061_merge_20201231_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcategory',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
