# Generated by Django 3.1.4 on 2021-01-03 08:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0062_auto_20210102_0754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='versionupdate',
            name='is_customer_app',
        ),
        migrations.RemoveField(
            model_name='versionupdate',
            name='is_waiter_app',
        ),
        migrations.RemoveField(
            model_name='versionupdate',
            name='version_no',
        ),
        migrations.AddField(
            model_name='versionupdate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='versionupdate',
            name='customer_app_version_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='versionupdate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='versionupdate',
            name='waiter_app_version_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
