# Generated by Django 3.1.4 on 2021-01-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0064_auto_20210103_0854'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='table',
            constraint=models.UniqueConstraint(fields=('restaurant', 'table_no'), name='restaurant and table no constrains'),
        ),
    ]
