# Generated by Django 3.1.1 on 2021-01-14 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0065_auto_20210103_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='clickable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discount',
            name='food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_slider', to='restaurant.food'),
        ),
        migrations.AddField(
            model_name='discount',
            name='is_popup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discount',
            name='serial_no',
            field=models.IntegerField(default=0),
        ),
    ]
