# Generated by Django 3.1.4 on 2021-01-17 12:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0066_auto_20210114_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='is_slider',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foodorder',
            name='order_no',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
