# Generated by Django 3.1.4 on 2021-01-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0067_auto_20210117_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodorder',
            name='order_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
