# Generated by Django 3.1.1 on 2021-01-20 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0068_auto_20210117_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='deleted_at',
        ),
    ]
