# Generated by Django 3.1.1 on 2021-01-24 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0069_remove_discount_deleted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printer_id', models.IntegerField(blank=True, null=True)),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_nodes', to='restaurant.foodorder')),
            ],
        ),
    ]
