# Generated by Django 3.1.1 on 2021-01-24 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0038_hotelstaffinformation_is_chef'),
        ('restaurant', '0070_printnode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printnode',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_nodes', to='restaurant.restaurant'),
        ),
        migrations.CreateModel(
            name='TakeAwayOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_staff', models.ManyToManyField(blank=True, related_name='take_away_orders', to='account_management.HotelStaffInformation')),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='take_away_orders', to='restaurant.restaurant')),
                ('running_order', models.ManyToManyField(blank=True, related_name='take_away_orders', to='restaurant.FoodOrder')),
            ],
        ),
    ]
