# Generated by Django 3.1.4 on 2021-01-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0072_parentcompanypromotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodorder',
            name='applied_promo_code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
