# Generated by Django 3.1.1 on 2021-02-17 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0074_versionupdate_build_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodorder',
            name='cash_received',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodorder',
            name='change_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodorder',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_orders', to='restaurant.paymenttype'),
        ),
    ]
