# Generated by Django 3.1.1 on 2021-03-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0076_cashlog_withdrawcash'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='discount_schedule_type',
            field=models.CharField(choices=[('Time_wise_offer', 'Time wise offer'), ('Date_wise_offer', 'Date wise offer')], default='Date_wise_offer', max_length=50),
        ),
        migrations.AddField(
            model_name='discount',
            name='discount_slot_closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='discount_slot_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodorder',
            name='discount_amount_is_percentage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foodorder',
            name='discount_base_amount',
            field=models.FloatField(default=False),
        ),
        migrations.AddField(
            model_name='foodorder',
            name='discount_given',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
