# Generated by Django 3.1.1 on 2021-03-07 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0038_hotelstaffinformation_is_chef'),
        ('restaurant', '0077_auto_20210302_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCodePromotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200, unique=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('promo_type', models.CharField(choices=[('PERCENTAGE', 'percentage'), ('AMOUNT', 'amount')], max_length=50)),
                ('max_amount', models.FloatField(default=0)),
                ('minimum_purchase_amount', models.FloatField(default=0)),
                ('amount', models.FloatField(default=0)),
                ('max_limit', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_code_promotions', to='restaurant.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='PromoCodePromotionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_code_promotion_logs', to='account_management.customerinfo')),
                ('promo_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_code_promotion_logs', to='restaurant.promocodepromotion')),
            ],
        ),
    ]
