# Generated by Django 3.1.4 on 2021-03-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0078_promocodepromotion_promocodepromotionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_service_charge_apply_in_original_food_price',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_vat_charge_apply_in_original_food_price',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
