# Generated by Django 3.1.4 on 2021-03-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0079_auto_20210314_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='is_service_charge_apply_in_original_food_price',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='is_vat_charge_apply_in_original_food_price',
            field=models.BooleanField(default=False),
        ),
    ]
