# Generated by Django 3.1.4 on 2021-03-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0080_auto_20210314_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='food',
            name='is_vat_applicable',
            field=models.BooleanField(default=False),
        ),
    ]
