# Generated by Django 3.1.4 on 2021-04-04 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0084_auto_20210404_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodorder',
            name='takeway_order_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_order_takeway_order_type', to='restaurant.takewayordertype'),
        ),
    ]
