# Generated by Django 3.1.4 on 2021-04-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0085_foodorder_takeway_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodorder',
            name='take_away_discount_amount_is_percentage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foodorder',
            name='take_away_discount_base_amount',
            field=models.FloatField(default=False),
        ),
        migrations.AddField(
            model_name='foodorder',
            name='take_away_discount_given',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
