# Generated by Django 3.1.4 on 2021-06-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0087_auto_20210428_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='sd_charge_percentage',
            field=models.FloatField(default=0.0),
        ),
    ]
